### ISSUE TITLE
OpenAI compatibility for open source models

### ISSUE THREAD

**Issue by DarinShapiroMS** [kaito-project/kaito#370]
Having a OpenAI compatible endpoints would make it easier for developers to use different models with the same code base. 

**Describe the solution you'd like**
Beyond just having the compatible endpoints, it should also be payload compatible for things like function calling and image upload.  I've seen the Json payload vary for both of those with different open-source models. 

**Describe alternatives you've considered**
Using a tool like LiteLLM to host the OpenAI compatible endpoints is what I use now, and it works with any models I can host with Ollama, for example.

**Comment by zhuangqh** [comment]
supported by using vllm. https://github.com/kaito-project/kaito/pull/635
