### ISSUE TITLE
Add document to explain chat template to end users

### ISSUE THREAD

**Issue by zhuangqh** [kaito-project/kaito#661]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Starting from transformers version 4.42, a chat template must be provided for chatting service. It's a low-level configuration file in jinja format that defines the constraints for [**chat message**](https://platform.openai.com/docs/api-reference/chat) input. See https://huggingface.co/docs/transformers/v4.43.4/en/chat_templating#templates-for-chat-models for more details.

It would be nice if we explain these rules to end users in natural language.

**Describe alternatives you've considered**

**Additional context**

**Comment by rudrakshkarpe** [comment]
Hi @zhuangqh , I'd love to wok on this issue :)

**Comment by rudrakshkarpe** [comment]
Thanks for assigning this issue to me @zhuangqh. 

I was wondering do we have any specific directory to store this documentation?

**Comment by rudrakshkarpe** [comment]
I have made this initial draft documentation [here](https://gist.github.com/rudrakshkarpe/1c2391feeb387691aef5a4a69c0259d0). Please let me know your thoughts on this and how we can further streamline it for the our use case here. 

Thank you!

**Comment by zhuangqh** [comment]
> I have made this initial draft documentation [here](https://gist.github.com/rudrakshkarpe/1c2391feeb387691aef5a4a69c0259d0). Please let me know your thoughts on this and how we can further streamline it for our use case here.
> 
> Thank you!

Thanks for your contribution. You can put this document here. https://github.com/kaito-project/kaito/tree/main/presets/workspace/inference/chat_templates

**Comment by rudrakshkarpe** [comment]
> > I have made this initial draft documentation [here](https://gist.github.com/rudrakshkarpe/1c2391feeb387691aef5a4a69c0259d0). Please let me know your thoughts on this and how we can further streamline it for our use case here.
> > Thank you!
> 
> Thanks for your contribution. You can put this document here. https://github.com/kaito-project/kaito/tree/main/presets/workspace/inference/chat_templates

Thanks for pointing out the directory. I've raised the #782 PR. Please take a look at it. I was also wondering if you guys have any community chat channel or community meetings where I discuss my doubts and learn more about the project?
