### ISSUE TITLE
`IDENTITY_CLIENT_ID` created but never used

### ISSUE THREAD

**Issue by surajssd** [kaito-project/kaito#723]
**Describe the bug**

In the [kaito installation documentation](https://github.com/kaito-project/kaito/blob/main/docs/installation.md#create-an-identity-and-assign-permissions) the steps asks users to create an `IDENTITY_CLIENT_ID` but it is never utilized anywhere. What is it for?

```bash
export IDENTITY_CLIENT_ID=$(az identity show --name $IDENTITY_NAME -g $RESOURCE_GROUP --subscription $SUBSCRIPTION --query 'clientId' -o tsv)
```

If it is a left over then it needs to be removed.

**Comment by ishaansehgal99** [comment]
Thanks for pointing this out! Fixed.
