### ISSUE TITLE
`inference_api.py` not found error when using custom deployment template

### ISSUE THREAD

**Issue by surajssd** [kaito-project/kaito#753]
**Describe the bug**

When deploying the custom deployment template defined [here](https://github.com/kaito-project/kaito/blob/main/docs/custom-model-integration/custom-deployment-template.yaml) the deployment complains `inference_api.py not found`.

I think this is because the work directory is set to `WORKDIR /workspace` in Dockerfile: https://github.com/kaito-project/kaito/blob/e0f28f00776c349bae10f7cac18c21a628194e84/docker/presets/models/tfs/Dockerfile#L8

Meanwhile the template is expecting the file to be in the work directory:

https://github.com/kaito-project/kaito/blob/e0f28f00776c349bae10f7cac18c21a628194e84/docs/custom-model-integration/custom-deployment-template.yaml#L25

But the file is not in `/workspace/inference_api.py` but it is in `/workspace/tfs/inference_api.py` and `/workspace/vllm/inference_api.py`:

https://github.com/kaito-project/kaito/blob/e0f28f00776c349bae10f7cac18c21a628194e84/docker/presets/models/tfs/Dockerfile#L18

https://github.com/kaito-project/kaito/blob/e0f28f00776c349bae10f7cac18c21a628194e84/docker/presets/models/tfs/Dockerfile#L27

**Steps To Reproduce**

Follow the documentation for option 2: https://github.com/kaito-project/kaito/blob/main/docs/custom-model-integration/custom-model-integration-guide.md#option-2-build-a-custom-docker-image-with-model-weights

**Expected behavior**

Either provide a comment here for users to modify:

https://github.com/kaito-project/kaito/blob/e0f28f00776c349bae10f7cac18c21a628194e84/docs/custom-model-integration/custom-deployment-template.yaml#L25

Or provide some parameterization so that the "correct" `inference_api.py` is used.

**Comment by ishaansehgal99** [comment]
Thanks for finding this! Yes we should be using `tfs/inference_api.py` as this file is using accelerate/transformers library. This file didn't account for new vllm release and is now updated (https://github.com/kaito-project/kaito/pull/757) thanks!
