### ISSUE TITLE
Do not copy `.git` folder when building the model images

### ISSUE THREAD

**Issue by surajssd** [kaito-project/kaito#764]
**Describe the bug**

The current build instructions / documentation for building the model images copies the `.git` folder from the model repository. This unnecessarily increases the size of the model image.

**Steps To Reproduce**

Build the `llama-2` model image using the following commands:

> [!NOTE]
> These instructions are adopted from: https://github.com/kati/kaito/blob/main/presets/workspace/models/llama2/README.md

```bash
# Ensure you are in the kaito directory
cd kaito
cd ..

export MODEL_ID="meta-llama/llama-2-70b"
git clone git@hf.co:$MODEL_ID

export VERSION="1cb3547"
export IMAGE_NAME="${MODEL_ID}:${VERSION}"
export WEIGHTS_PATH="$(basename ${MODEL_ID})"

docker build \
    -t "${IMAGE_NAME}" \
    --file kaito/docker/presets/models/llama-2/Dockerfile \
    --build-arg WEIGHTS_PATH=${WEIGHTS_PATH} \
    --build-arg MODEL_TYPE=llama2-completion \
    --build-arg VERSION=${VERSION} \
    --push \
    ./
```

**Analysis**

Once the image is built, we can see that it is 289GB in size:

```console
$ docker images
REPOSITORY                              TAG               IMAGE ID       CREATED        SIZE
meta-llama/llama-2-70b                  1cb3547           4715d3ed9f6b   10 hours ago   289GB
```

And it is in the same size range as you see in the local directory:

```console
✔ ~/work/llama-2-70b [main|✔]
$ du -sh .
257G    .
```

Now if we inspect it from within the image:

```console
$ docker run -it meta-llama/llama-2-70b:1cb3547 bash
root@281f86e2288d:/workspace/llama#
```

Go to the [weights folder](https://github.com/kaito-project/kaito/blob/11f9cd1fecd7c5ae49dca6b9e4c3132bd291ef98/docker/presets/models/llama-2/Dockerfile#L32):

```bash
root@281f86e2288d:/workspace/llama# cd /workspace/llama/llama-2/weights
root@281f86e2288d:/workspace/llama/llama-2/weights#
```

Now if we see the size of the weights folder, we can see that it matches the same size as we saw from outside the container image which is `257GB`:

```console
root@281f86e2288d:/workspace/llama/llama-2/weights# du -sh .
257G    .
```

But if we see the individual files in the weights folder, we can see that the `.git` folder is taking up a lot of space of 129GB:

```bash
root@281f86e2288d:/workspace/llama/llama-2/weights# du -sh *
8.0K    LICENSE.txt
24K     README.md
1.2M    Responsible-Use-Guide.pdf
8.0K    USE_POLICY.md
4.0K    checksum.chk
17G     consolidated.00.pth
17G     consolidated.01.pth
17G     consolidated.02.pth
17G     consolidated.03.pth
17G     consolidated.04.pth
17G     consolidated.05.pth
17G     consolidated.06.pth
17G     consolidated.07.pth
4.0K    params.json
492K    tokenizer.model
4.0K    tokenizer_checklist.chk

root@281f86e2288d:/workspace/llama/llama-2/weights# du -sh .git
129G    .git
```

So the `.git` folder is taking up a lot of space in the image. This is unnecessary as the `.git` folder is not needed in the image.

**Expected behavior**

Figure out a way to not copy the `.git` folder when building the model image. I know weights path is outside the control of the project, but either we can categorically avoid copying `.git` folders or we can add a `.dockerignore` file in the model repository to ignore the `.git` folder, whichever is less intrusive!

**Comment by ishaansehgal99** [comment]
Luckily we do not include `.git` folders in the process of building our preset images. Here we store .git files in a separate directory during build process.

`https://github.com/kaito-project/kaito/blob/857c373d6628046fb32056361f7b1afbf93f899e/.github/workflows/kind-cluster/main.py#L53-L72`
